# Generated by Django 4.1.1 on 2023-08-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='moqim', unique=True),
            preserve_default=False,
        ),
    ]
